-- =========================================================================================
-- SCAF - MIGRACIÓN Y ESQUEMA OPTIMIZADO V2 (DATA PRESERVATION)
-- Este script crea las nuevas tablas y MIGRA los datos existentes.
-- Corrige el conflicto de nombres con "Roles" (SQL Server es case-insensitive por defecto)
-- y añade las tablas de tareas que faltaban.
-- =========================================================================================

USE SCAF_DB;
GO

-- 1. CREAR NUEVAS TABLAS (Si no existen)

-- [Configuración y Seguridad]
IF OBJECT_ID('CONFIG_EMP', 'U') IS NULL
CREATE TABLE CONFIG_EMP (
    ID INT PRIMARY KEY DEFAULT 1,
    NOMBRE VARCHAR(200) NOT NULL DEFAULT 'Mi Empresa S.A.',
    NIT VARCHAR(50) NOT NULL DEFAULT '',
    CORREO VARCHAR(100) NOT NULL DEFAULT '',
    TEL VARCHAR(50) NOT NULL DEFAULT '',
    DIR VARCHAR(500) NOT NULL DEFAULT '',
    MONEDA VARCHAR(10) NOT NULL DEFAULT 'USD',
    TEMA VARCHAR(50) NOT NULL DEFAULT 'light',
    FEC_ACT DATETIME NOT NULL DEFAULT GETUTCDATE()
);

-- Usamos ROL en singular para evitar choque con la tabla antigua 'Roles'
IF OBJECT_ID('ROL', 'U') IS NULL
CREATE TABLE ROL (
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    PERMISOS NVARCHAR(MAX) NOT NULL DEFAULT '[]',
    FEC_CREA DATETIME NOT NULL DEFAULT GETUTCDATE()
);

IF OBJECT_ID('USUARIOS', 'U') IS NULL
CREATE TABLE USUARIOS (
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    CORREO VARCHAR(100) NOT NULL,
    ID_ROL VARCHAR(50) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NULL,
    ACTIVO BIT NOT NULL DEFAULT 1,
    FEC_CREA DATETIME NOT NULL DEFAULT GETUTCDATE(),
    FEC_ACT DATETIME NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT UQ_USUARIOS_CORREO UNIQUE (CORREO),
    CONSTRAINT FK_USR_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID)
);

-- [Catálogos]
IF OBJECT_ID('PROVEEDOR', 'U') IS NULL
CREATE TABLE PROVEEDOR (
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(150) NOT NULL,
    CONTACTO VARCHAR(100) NULL,
    TEL VARCHAR(50) NULL,
    CORREO VARCHAR(100) NULL,
    DIR VARCHAR(255) NULL,
    CALIF INT NULL CHECK (CALIF BETWEEN 1 AND 5),
    ACTIVO BIT NOT NULL DEFAULT 1,
    FEC_CREA DATETIME NOT NULL DEFAULT GETUTCDATE()
);

IF OBJECT_ID('CATEGORIAS', 'U') IS NULL
CREATE TABLE CATEGORIAS (
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    ID_PADRE VARCHAR(50) NULL,
    CONSTRAINT FK_CAT_PADRE FOREIGN KEY (ID_PADRE) REFERENCES CATEGORIAS(ID)
);

IF OBJECT_ID('ORG', 'U') IS NULL
CREATE TABLE ORG (
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    ID_PADRE VARCHAR(50) NULL,
    CONSTRAINT FK_ORG_PADRE FOREIGN KEY (ID_PADRE) REFERENCES ORG(ID)
);

IF OBJECT_ID('TIPOS_MANT', 'U') IS NULL
CREATE TABLE TIPOS_MANT (
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    PREVENTIVO BIT NOT NULL DEFAULT 1
);

-- [Activos]
IF OBJECT_ID('ACTIVOS', 'U') IS NULL
CREATE TABLE ACTIVOS (
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(150) NOT NULL,
    MARCA VARCHAR(100) NULL,
    MODELO VARCHAR(100) NULL,
    SERIAL VARCHAR(100) NULL,
    ID_CAT VARCHAR(50) NOT NULL,
    FAMILIA VARCHAR(100) NULL,
    SUBFAM VARCHAR(100) NULL,
    ID_DEP VARCHAR(50) NULL,
    UBICACION VARCHAR(200) NULL,
    AREA VARCHAR(100) NULL,
    ID_CUST VARCHAR(50) NULL,
    ID_PROV VARCHAR(50) NULL,
    FEC_ING DATE NOT NULL DEFAULT CAST(GETUTCDATE() AS DATE),
    COSTO_ACQ DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    VALOR_ACT DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    ESTADO VARCHAR(50) NOT NULL DEFAULT 'ACTIVO',
    DESCRIP NVARCHAR(MAX) NULL,
    OBS NVARCHAR(MAX) NULL,
    BORRADO BIT NOT NULL DEFAULT 0,
    FEC_BORR DATETIME NULL,
    FEC_CREA DATETIME NOT NULL DEFAULT GETUTCDATE(),
    FEC_ACT DATETIME NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT UQ_ACT_SERIAL UNIQUE (SERIAL),
    CONSTRAINT FK_ACT_CAT FOREIGN KEY (ID_CAT) REFERENCES CATEGORIAS(ID),
    CONSTRAINT FK_ACT_DEP FOREIGN KEY (ID_DEP) REFERENCES ORG(ID),
    CONSTRAINT FK_ACT_CUST FOREIGN KEY (ID_CUST) REFERENCES USUARIOS(ID),
    CONSTRAINT FK_ACT_PROV FOREIGN KEY (ID_PROV) REFERENCES PROVEEDOR(ID)
);

-- [Mantenimiento]
IF OBJECT_ID('PLANES', 'U') IS NULL
CREATE TABLE PLANES (
    ID VARCHAR(100) NOT NULL PRIMARY KEY,
    CODIGO VARCHAR(50) NOT NULL,
    DESCRIP VARCHAR(255) NOT NULL,
    CATEGORIA VARCHAR(100) NULL,
    SUBFAM VARCHAR(100) NULL,
    FRECUENCIA VARCHAR(50) NOT NULL DEFAULT 'Mensual',
    ACTIVO BIT NOT NULL DEFAULT 1,
    FEC_CREA DATETIME NOT NULL DEFAULT GETUTCDATE()
);

-- NUEVO: Tareas de los Planes
IF OBJECT_ID('TAREAS_PLAN', 'U') IS NULL
CREATE TABLE TAREAS_PLAN (
    ID VARCHAR(100) NOT NULL PRIMARY KEY,
    ID_PLAN VARCHAR(100) NOT NULL,
    TAREA NVARCHAR(MAX) NOT NULL,
    FRECUENCIA VARCHAR(50) NOT NULL DEFAULT 'Mensual',
    CONSTRAINT FK_TPLAN_PLAN FOREIGN KEY (ID_PLAN) REFERENCES PLANES(ID)
);

IF OBJECT_ID('ORDENES_TRAB', 'U') IS NULL
CREATE TABLE ORDENES_TRAB (
    ID VARCHAR(100) NOT NULL PRIMARY KEY,
    NOM_PLAN VARCHAR(200) NOT NULL,
    ID_ACT VARCHAR(50) NOT NULL,
    FEC_INI DATE NOT NULL,
    FEC_FIN DATE NULL,
    ID_ASIG VARCHAR(50) NULL,
    NOTAS NVARCHAR(MAX) NULL,
    ESTADO VARCHAR(50) NOT NULL DEFAULT 'PROGRAMADO',
    FEC_CREA DATETIME NOT NULL DEFAULT GETUTCDATE(),
    FEC_ACT DATETIME NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT FK_OT_ACT FOREIGN KEY (ID_ACT) REFERENCES ACTIVOS(ID),
    CONSTRAINT FK_OT_ASIG FOREIGN KEY (ID_ASIG) REFERENCES USUARIOS(ID)
);

IF OBJECT_ID('TICKETS', 'U') IS NULL
CREATE TABLE TICKETS (
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    ID_OT VARCHAR(100) NULL,
    ID_ACT VARCHAR(50) NOT NULL,
    ID_PLAN VARCHAR(100) NULL,
    TITULO VARCHAR(200) NOT NULL,
    ID_TIPO VARCHAR(50) NOT NULL,
    ID_PROV VARCHAR(50) NULL,
    ID_ASIG VARCHAR(50) NULL,
    FEC_INI DATE NOT NULL,
    FEC_FIN DATE NULL,
    ESTADO VARCHAR(50) NOT NULL DEFAULT 'PENDIENTE',
    COSTO DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    DESCRIP NVARCHAR(MAX) NULL,
    BORRADO BIT NOT NULL DEFAULT 0,
    FEC_CREA DATETIME NOT NULL DEFAULT GETUTCDATE(),
    FEC_ACT DATETIME NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT FK_TICK_OT FOREIGN KEY (ID_OT) REFERENCES ORDENES_TRAB(ID),
    CONSTRAINT FK_TICK_ACT FOREIGN KEY (ID_ACT) REFERENCES ACTIVOS(ID),
    CONSTRAINT FK_TICK_PLAN FOREIGN KEY (ID_PLAN) REFERENCES PLANES(ID),
    CONSTRAINT FK_TICK_TIPO FOREIGN KEY (ID_TIPO) REFERENCES TIPOS_MANT(ID),
    CONSTRAINT FK_TICK_PROV FOREIGN KEY (ID_PROV) REFERENCES PROVEEDOR(ID),
    CONSTRAINT FK_TICK_ASIG FOREIGN KEY (ID_ASIG) REFERENCES USUARIOS(ID)
);

-- NUEVO: Tareas por Ticket (Checklists)
IF OBJECT_ID('TAREAS_TICK', 'U') IS NULL
CREATE TABLE TAREAS_TICK (
    ID VARCHAR(100) NOT NULL PRIMARY KEY,
    ID_TICKET VARCHAR(50) NOT NULL,
    TAREA NVARCHAR(MAX) NOT NULL,
    COMPLETADO BIT NOT NULL DEFAULT 0,
    FEC_COMP DATETIME NULL,
    CONSTRAINT FK_TTICK_TICKET FOREIGN KEY (ID_TICKET) REFERENCES TICKETS(ID)
);

-- [Auditoría]
IF OBJECT_ID('AUDITORIA', 'U') IS NULL
CREATE TABLE AUDITORIA (
    ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    FECHA DATETIME NOT NULL DEFAULT GETUTCDATE(),
    ACCION VARCHAR(50) NOT NULL,
    ENTIDAD VARCHAR(100) NOT NULL,
    ID_ENT VARCHAR(100) NOT NULL,
    DESCRIP NVARCHAR(MAX) NULL,
    ID_USR VARCHAR(50) NULL,
    NOM_USR VARCHAR(100) NULL,
    CAMBIOS NVARCHAR(MAX) NULL
);

GO

-- ==========================================
-- 2. LÓGICA DE MIGRACIÓN (MOVER DATOS)
-- ==========================================

PRINT 'Iniciando migración de datos...';

-- Migrar Roles a ROL
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'Roles')
AND NOT EXISTS (SELECT TOP 1 1 FROM ROL)
BEGIN
    INSERT INTO ROL (ID, NOMBRE, PERMISOS)
    SELECT Id, Name, Permissions FROM Roles;
    PRINT 'Roles migrados a ROL.';
END

-- Migrar Usuarios
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'Users')
AND NOT EXISTS (SELECT TOP 1 1 FROM USUARIOS)
BEGIN
    INSERT INTO USUARIOS (ID, NOMBRE, CORREO, ID_ROL)
    SELECT Id, Name, Email, RoleId FROM Users;
    PRINT 'Usuarios migrados.';
END

-- Migrar Proveedores
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'Suppliers')
AND NOT EXISTS (SELECT TOP 1 1 FROM PROVEEDOR)
BEGIN
    INSERT INTO PROVEEDOR (ID, NOMBRE, CONTACTO, TEL, CORREO, DIR)
    SELECT Id, Name, Contact, Phone, Email, Address FROM Suppliers;
    PRINT 'Proveedores migrados.';
END

-- Migrar Categorías
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'AssetCategories')
AND NOT EXISTS (SELECT TOP 1 1 FROM CATEGORIAS)
BEGIN
    INSERT INTO CATEGORIAS (ID, NOMBRE, ID_PADRE)
    SELECT Id, Name, ParentId FROM AssetCategories;
    PRINT 'Categorías migradas.';
END

-- Migrar Org
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'Organization')
AND NOT EXISTS (SELECT TOP 1 1 FROM ORG)
BEGIN
    INSERT INTO ORG (ID, NOMBRE, ID_PADRE)
    SELECT Id, Name, ParentId FROM Organization;
    PRINT 'Organización migrada.';
END

-- Migrar Tipos Mant
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'MaintenanceTypes')
AND NOT EXISTS (SELECT TOP 1 1 FROM TIPOS_MANT)
BEGIN
    INSERT INTO TIPOS_MANT (ID, NOMBRE)
    SELECT Id, Name FROM MaintenanceTypes;
    PRINT 'Tipos de mantenimiento migrados.';
END

-- Migrar Activos
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'Assets')
AND NOT EXISTS (SELECT TOP 1 1 FROM ACTIVOS)
BEGIN
    INSERT INTO ACTIVOS (ID, NOMBRE, MARCA, MODELO, SERIAL, ID_CAT, FAMILIA, SUBFAM, ID_DEP, ID_CUST, ID_PROV, FEC_ING, COSTO_ACQ, ESTADO, DESCRIP)
    SELECT Id, Name, Brand, Model, Serial, CategoryId, Family, SubFamily, DepartmentId, CustodioId, SupplierId, EntryDate, AcquisitionCost, Status, Description FROM Assets;
    PRINT 'Activos migrados.';
END

-- Migrar Planes
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'MaintenancePlans')
AND NOT EXISTS (SELECT TOP 1 1 FROM PLANES)
BEGIN
    INSERT INTO PLANES (ID, CODIGO, DESCRIP, SUBFAM, CATEGORIA, FRECUENCIA)
    SELECT Id, Code, Description, SubFamily, Category, PlanFrequency FROM MaintenancePlans;
    PRINT 'Planes migrados.';
END

-- Migrar Tareas de Planes
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'MaintenancePlanTasks')
AND NOT EXISTS (SELECT TOP 1 1 FROM TAREAS_PLAN)
BEGIN
    INSERT INTO TAREAS_PLAN (ID, ID_PLAN, TAREA, FRECUENCIA)
    SELECT Id, PlanId, TaskDescription, Frequency FROM MaintenancePlanTasks;
    PRINT 'Tareas de planes migradas.';
END

-- Migrar Tickets
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'Maintenances')
AND NOT EXISTS (SELECT TOP 1 1 FROM TICKETS)
BEGIN
    INSERT INTO TICKETS (ID, ID_ACT, TITULO, ID_TIPO, ID_PROV, ID_ASIG, FEC_INI, FEC_FIN, ESTADO, COSTO, DESCRIP, ID_OT, ID_PLAN)
    SELECT Id, AssetId, Title, TypeId, ProviderId, AssignedUserId, StartDate, EndDate, Status, Cost, Description, WorkOrderId, PlanId FROM Maintenances;
    PRINT 'Tickets migrados.';
END

-- Migrar Tareas de Tickets
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'MaintenanceTicketTasks')
AND NOT EXISTS (SELECT TOP 1 1 FROM TAREAS_TICK)
BEGIN
    INSERT INTO TAREAS_TICK (ID, ID_TICKET, TAREA, COMPLETADO, FEC_COMP)
    SELECT Id, TicketId, TaskDescription, IsCompleted, CompletedAt FROM MaintenanceTicketTasks;
    PRINT 'Checklists de tickets migrados.';
END

-- Migrar Configuración
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'CompanyConfig')
AND NOT EXISTS (SELECT TOP 1 1 FROM CONFIG_EMP)
BEGIN
    INSERT INTO CONFIG_EMP (ID, NOMBRE, NIT, CORREO, TEL, DIR, MONEDA, TEMA)
    SELECT Id, Name, Nit, Email, Phone, Address, Currency, Theme FROM CompanyConfig;
    PRINT 'Configuración migrada.';
END

GO

PRINT 'Migración completada con éxito. Puedes proceder a renombrar o eliminar las tablas antiguas manualmente si lo deseas.';
