-- ============================================================
-- MIGRACION: Clasificacion de Activos por IDs (FK a CATEGORIA)
-- Reemplaza FAMILIA (texto) y SUBFAM (texto) por FKs reales
-- ============================================================

-- 1. Agregar nuevas columnas FK
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ACTIVO' AND COLUMN_NAME='ID_SECCION')
  ALTER TABLE ACTIVO ADD ID_SECCION VARCHAR(50) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ACTIVO' AND COLUMN_NAME='ID_FAMILIA')
  ALTER TABLE ACTIVO ADD ID_FAMILIA VARCHAR(50) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ACTIVO' AND COLUMN_NAME='ID_SUBFAMILIA')
  ALTER TABLE ACTIVO ADD ID_SUBFAMILIA VARCHAR(50) NULL;
GO

-- 2. Migrar FAMILIA simple (texto = nombre de seccion hija de la categoria)
UPDATE a SET
  a.ID_SECCION = sec.ID
FROM ACTIVO a
INNER JOIN CATEGORIA sec ON sec.[NOMBRE] = a.FAMILIA AND sec.ID_PADRE = a.ID_CATEGORIA
WHERE a.FAMILIA IS NOT NULL
  AND a.FAMILIA <> ''
  AND a.FAMILIA NOT LIKE '% > %'
  AND a.ID_CATEGORIA IS NOT NULL
  AND a.ID_SECCION IS NULL;
GO

-- 3. Migrar FAMILIA con formato "Seccion > Familia"
UPDATE a SET
  a.ID_SECCION = sec.ID
FROM ACTIVO a
INNER JOIN CATEGORIA sec
  ON sec.[NOMBRE] = LEFT(a.FAMILIA, CHARINDEX(' > ', a.FAMILIA + ' > ') - 1)
  AND sec.ID_PADRE = a.ID_CATEGORIA
WHERE a.FAMILIA LIKE '% > %'
  AND a.ID_CATEGORIA IS NOT NULL
  AND a.ID_SECCION IS NULL;
GO

-- 4. Migrar SUBFAM (texto) como hijo de la seccion ya vinculada
UPDATE a SET
  a.ID_FAMILIA = fam.ID
FROM ACTIVO a
INNER JOIN CATEGORIA fam ON fam.[NOMBRE] = a.SUBFAM AND fam.ID_PADRE = a.ID_SECCION
WHERE a.SUBFAM IS NOT NULL
  AND a.SUBFAM <> ''
  AND a.ID_SECCION IS NOT NULL
  AND a.ID_FAMILIA IS NULL;
GO

PRINT 'Migracion de clasificacion de activos completada.';
GO

-- ============================================================
-- 5. Eliminar columnas obsoletas FAMILIA y SUBFAM
-- ============================================================
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ACTIVO' AND COLUMN_NAME='FAMILIA')
  ALTER TABLE ACTIVO DROP COLUMN FAMILIA;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ACTIVO' AND COLUMN_NAME='SUBFAM')
  ALTER TABLE ACTIVO DROP COLUMN SUBFAM;
GO

-- Eliminar ID_SCOPE duplicado (el scope se obtiene via ID_CATEGORIA -> CATEGORIA.ID_SCOPE)
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ACTIVO' AND COLUMN_NAME='ID_SCOPE')
  ALTER TABLE ACTIVO DROP COLUMN ID_SCOPE;
GO

PRINT 'Columnas FAMILIA, SUBFAM e ID_SCOPE eliminadas de la tabla ACTIVO.';
GO
