-- ============================================================
-- SCAF: Índices de rendimiento y extensión de configuración
-- Ejecutar sobre SCAF_DB después de aplicar el schema principal
-- ============================================================

-- ── Índices secundarios ─────────────────────────────────────
-- Evitan full table scans en las consultas más frecuentes

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_ACTIVOS_BORRADO')
  CREATE INDEX IX_ACTIVOS_BORRADO ON ACTIVOS(BORRADO) INCLUDE (NOMBRE, ESTADO, COSTO_ACQ, VALOR_ACT);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_ACTIVOS_ESTADO')
  CREATE INDEX IX_ACTIVOS_ESTADO ON ACTIVOS(ESTADO) WHERE BORRADO = 0;

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_ACTIVOS_ID_CAT')
  CREATE INDEX IX_ACTIVOS_ID_CAT ON ACTIVOS(ID_CAT) WHERE BORRADO = 0;

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_ACTIVOS_FEC_CREA')
  CREATE INDEX IX_ACTIVOS_FEC_CREA ON ACTIVOS(FEC_CREA DESC) WHERE BORRADO = 0;

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TICKETS_ID_ACT')
  CREATE INDEX IX_TICKETS_ID_ACT ON TICKETS(ID_ACT) WHERE BORRADO = 0;

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TICKETS_ESTADO')
  CREATE INDEX IX_TICKETS_ESTADO ON TICKETS(ESTADO) WHERE BORRADO = 0;

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TICKETS_FEC_FIN')
  CREATE INDEX IX_TICKETS_FEC_FIN ON TICKETS(FEC_FIN) WHERE BORRADO = 0;

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TICKETS_ID_PLAN')
  CREATE INDEX IX_TICKETS_ID_PLAN ON TICKETS(ID_PLAN) WHERE BORRADO = 0;

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_USUARIOS_ID_ROL')
  CREATE INDEX IX_USUARIOS_ID_ROL ON USUARIOS(ID_ROL);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_AUDITORIA_FECHA')
  CREATE INDEX IX_AUDITORIA_FECHA ON AUDITORIA(FECHA DESC);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_AUDITORIA_ENTIDAD')
  CREATE INDEX IX_AUDITORIA_ENTIDAD ON AUDITORIA(ENTIDAD, FECHA DESC);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TAREAS_PLAN_ID_PLAN')
  CREATE INDEX IX_TAREAS_PLAN_ID_PLAN ON TAREAS_PLAN(ID_PLAN);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TAREAS_TICK_ID_TICKET')
  CREATE INDEX IX_TAREAS_TICK_ID_TICKET ON TAREAS_TICK(ID_TICKET);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_ORDENES_ESTADO')
  CREATE INDEX IX_ORDENES_ESTADO ON ORDENES_TRAB(ESTADO);

-- ── Extensión de CONFIG_EMP ──────────────────────────────────
-- Nuevas columnas de configuración de negocio

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CONFIG_EMP') AND name = 'DIAS_ALERTA_MANT')
  ALTER TABLE CONFIG_EMP ADD DIAS_ALERTA_MANT INT NOT NULL DEFAULT 15;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CONFIG_EMP') AND name = 'ITEMS_POR_PAGINA')
  ALTER TABLE CONFIG_EMP ADD ITEMS_POR_PAGINA INT NOT NULL DEFAULT 50;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CONFIG_EMP') AND name = 'MONEDA_SIMBOLO')
  ALTER TABLE CONFIG_EMP ADD MONEDA_SIMBOLO VARCHAR(10) NOT NULL DEFAULT '$';

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('CONFIG_EMP') AND name = 'PERMITIR_BORRADO')
  ALTER TABLE CONFIG_EMP ADD PERMITIR_BORRADO BIT NOT NULL DEFAULT 1;

PRINT 'Índices y columnas de configuración aplicados correctamente.';
