USE SCAF_DB;
GO

-- 1. ELIMINAR TABLAS EXISTENTES (Limpieza Total)
IF OBJECT_ID('TAREAS_TICK', 'U') IS NOT NULL DROP TABLE TAREAS_TICK;
IF OBJECT_ID('TAREAS_PLAN', 'U') IS NOT NULL DROP TABLE TAREAS_PLAN;
IF OBJECT_ID('TICKETS', 'U') IS NOT NULL DROP TABLE TICKETS;
IF OBJECT_ID('ORDENES_TRAB', 'U') IS NOT NULL DROP TABLE ORDENES_TRAB;
IF OBJECT_ID('ACTIVOS', 'U') IS NOT NULL DROP TABLE ACTIVOS;
IF OBJECT_ID('PLANES', 'U') IS NOT NULL DROP TABLE PLANES;
IF OBJECT_ID('USUARIOS', 'U') IS NOT NULL DROP TABLE USUARIOS;
IF OBJECT_ID('ROL', 'U') IS NOT NULL DROP TABLE ROL;
IF OBJECT_ID('PROVEEDOR', 'U') IS NOT NULL DROP TABLE PROVEEDOR;
IF OBJECT_ID('CATEGORIAS', 'U') IS NOT NULL DROP TABLE CATEGORIAS;
IF OBJECT_ID('ORG', 'U') IS NOT NULL DROP TABLE ORG;
IF OBJECT_ID('TIPOS_MANT', 'U') IS NOT NULL DROP TABLE TIPOS_MANT;
IF OBJECT_ID('AUDITORIA', 'U') IS NOT NULL DROP TABLE AUDITORIA;
IF OBJECT_ID('CONFIG_EMP', 'U') IS NOT NULL DROP TABLE CONFIG_EMP;
GO

-- 2. CREACIÓN DEL NUEVO ESQUEMA PROFESIONAL (COMPLETO)
CREATE TABLE CONFIG_EMP (
    ID INT PRIMARY KEY DEFAULT 1,
    NOMBRE VARCHAR(200) NOT NULL DEFAULT 'SCAF SISTEMA',
    NIT VARCHAR(50) DEFAULT '',
    CORREO VARCHAR(100) DEFAULT '',
    TEL VARCHAR(50) DEFAULT '',
    DIR VARCHAR(500) DEFAULT '',
    MONEDA VARCHAR(10) DEFAULT 'USD',
    TEMA VARCHAR(50) DEFAULT 'dark',
    FEC_ACT DATETIME DEFAULT GETUTCDATE()
);
GO
INSERT INTO CONFIG_EMP (ID, NOMBRE) VALUES (1, 'SCAF SISTEMA');
GO

CREATE TABLE ROL (
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    PERMISOS NVARCHAR(MAX) NOT NULL DEFAULT '[]',
    FEC_CREA DATETIME NOT NULL DEFAULT GETUTCDATE()
);
GO

CREATE TABLE USUARIOS (
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    CORREO VARCHAR(100) UNIQUE NOT NULL DEFAULT '',
    USERNAME VARCHAR(50) NULL,
    ID_ROL VARCHAR(50) FOREIGN KEY REFERENCES ROL(ID),
    PASSWORD_HASH VARCHAR(255) NULL,
    ACTIVO BIT NOT NULL DEFAULT 1,
    FEC_CREA DATETIME NOT NULL DEFAULT GETUTCDATE(),
    FEC_ACT DATETIME NOT NULL DEFAULT GETUTCDATE()
);
GO

CREATE TABLE PROVEEDOR (
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(150) NOT NULL,
    CONTACTO VARCHAR(100),
    TEL VARCHAR(50),
    CORREO VARCHAR(100),
    DIR VARCHAR(255),
    CALIF INT CHECK (CALIF BETWEEN 1 AND 5),
    ACTIVO BIT NOT NULL DEFAULT 1,
    FEC_CREA DATETIME NOT NULL DEFAULT GETUTCDATE()
);
GO

CREATE TABLE CATEGORIAS (
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    ID_PADRE VARCHAR(50) FOREIGN KEY REFERENCES CATEGORIAS(ID)
);
GO

CREATE TABLE ORG (
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    ID_PADRE VARCHAR(50) FOREIGN KEY REFERENCES ORG(ID)
);
GO

CREATE TABLE TIPOS_MANT (
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    PREVENTIVO BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE ACTIVOS (
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(150) NOT NULL,
    MARCA VARCHAR(100),
    MODELO VARCHAR(100),
    SERIAL VARCHAR(100) UNIQUE,
    ID_CAT VARCHAR(50) FOREIGN KEY REFERENCES CATEGORIAS(ID),
    FAMILIA VARCHAR(100),
    SUBFAM VARCHAR(100),
    ID_DEP VARCHAR(50) FOREIGN KEY REFERENCES ORG(ID),
    UBICACION VARCHAR(200),
    AREA VARCHAR(100),
    ID_CUST VARCHAR(50) FOREIGN KEY REFERENCES USUARIOS(ID),
    ID_PROV VARCHAR(50) FOREIGN KEY REFERENCES PROVEEDOR(ID),
    FEC_ING DATE NOT NULL DEFAULT CAST(GETUTCDATE() AS DATE),
    COSTO_ACQ DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    VALOR_ACT DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    ESTADO VARCHAR(50) NOT NULL DEFAULT 'ACTIVO',
    DESCRIP NVARCHAR(MAX),
    OBS NVARCHAR(MAX),
    BORRADO BIT NOT NULL DEFAULT 0,
    FEC_BORR DATETIME,
    FEC_CREA DATETIME NOT NULL DEFAULT GETUTCDATE(),
    FEC_ACT DATETIME NOT NULL DEFAULT GETUTCDATE()
);
GO

CREATE TABLE PLANES (
    ID VARCHAR(100) NOT NULL PRIMARY KEY,
    CODIGO VARCHAR(50) NOT NULL,
    DESCRIP VARCHAR(255) NOT NULL,
    CATEGORIA VARCHAR(100),
    SUBFAM VARCHAR(100),
    FRECUENCIA VARCHAR(50) NOT NULL DEFAULT 'Mensual',
    ACTIVO BIT NOT NULL DEFAULT 1,
    FEC_CREA DATETIME NOT NULL DEFAULT GETUTCDATE()
);
GO

CREATE TABLE TAREAS_PLAN (
    ID VARCHAR(100) NOT NULL PRIMARY KEY,
    ID_PLAN VARCHAR(100) FOREIGN KEY REFERENCES PLANES(ID),
    TAREA NVARCHAR(MAX) NOT NULL,
    FRECUENCIA VARCHAR(50) NOT NULL DEFAULT 'Mensual'
);
GO

CREATE TABLE ORDENES_TRAB (
    ID VARCHAR(100) NOT NULL PRIMARY KEY,
    NOM_PLAN VARCHAR(200) NOT NULL,
    ID_ACT VARCHAR(50) FOREIGN KEY REFERENCES ACTIVOS(ID),
    FEC_INI DATE NOT NULL,
    FEC_FIN DATE,
    ID_ASIG VARCHAR(50) FOREIGN KEY REFERENCES USUARIOS(ID),
    NOTAS NVARCHAR(MAX),
    ESTADO VARCHAR(50) NOT NULL DEFAULT 'PROGRAMADO',
    FEC_CREA DATETIME NOT NULL DEFAULT GETUTCDATE(),
    FEC_ACT DATETIME NOT NULL DEFAULT GETUTCDATE()
);
GO

CREATE TABLE TICKETS (
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    ID_OT VARCHAR(100) FOREIGN KEY REFERENCES ORDENES_TRAB(ID),
    ID_ACT VARCHAR(50) FOREIGN KEY REFERENCES ACTIVOS(ID),
    ID_PLAN VARCHAR(100) FOREIGN KEY REFERENCES PLANES(ID),
    TITULO VARCHAR(200) NOT NULL,
    ID_TIPO VARCHAR(50) FOREIGN KEY REFERENCES TIPOS_MANT(ID),
    ID_PROV VARCHAR(50) FOREIGN KEY REFERENCES PROVEEDOR(ID),
    ID_ASIG VARCHAR(50) FOREIGN KEY REFERENCES USUARIOS(ID),
    FEC_INI DATE NOT NULL,
    FEC_FIN DATE,
    ESTADO VARCHAR(50) NOT NULL DEFAULT 'PENDIENTE',
    COSTO DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    DESCRIP NVARCHAR(MAX),
    BORRADO BIT NOT NULL DEFAULT 0,
    FEC_CREA DATETIME NOT NULL DEFAULT GETUTCDATE(),
    FEC_ACT DATETIME NOT NULL DEFAULT GETUTCDATE()
);
GO

CREATE TABLE TAREAS_TICK (
    ID VARCHAR(100) NOT NULL PRIMARY KEY,
    ID_TICKET VARCHAR(50) FOREIGN KEY REFERENCES TICKETS(ID),
    TAREA NVARCHAR(MAX) NOT NULL,
    COMPLETADO BIT NOT NULL DEFAULT 0,
    FEC_COMP DATETIME
);
GO

CREATE TABLE AUDITORIA (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    FECHA DATETIME DEFAULT GETUTCDATE(),
    ACCION VARCHAR(50),
    ENTIDAD VARCHAR(100),
    ID_ENT VARCHAR(100),
    DESCRIP NVARCHAR(MAX),
    ID_USR VARCHAR(50),
    NOM_USR VARCHAR(100),
    CAMBIOS NVARCHAR(MAX)
);
GO

-- DATOS BASE: Solo el rol SUPERADMIN. El usuario admin se crea con create-superadmin.js
INSERT INTO ROL (ID, NOMBRE, PERMISOS) VALUES ('SUPERADMIN', 'Super Administrador', '["all"]');

GO
PRINT 'ESQUEMA RECONSTRUIDO AL 100% CON TODAS LAS COLUMNAS.';
